apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: eherlim
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20  
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:              
      - name: app-deployment
        image: harbor.dev.afsmtddso.com/eherlim-harbor-project/app:49d0fd3-3b2da0e
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: db-secret
